In [14]:
%pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
import numpy as np

# partie 1

  1) Créer une liste Python stockant ces températures

une liste python est une structure générique. pour créer une liste sur python on utilise les [ ].

In [16]:
temperature = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperature)

[24.5, 25.1, 26.3, 27.0, 25.8]


2) Créer un tableau NumPy équivalent stockant ces températures

pour créer un tableau numpy on utilise la fonction np.array()

In [17]:
tableau = np.array([24.5, 25.1, 26.3, 27.0, 25.8 ])
print(f"tableau ={tableau}")


tableau =[24.5 25.1 26.3 27.  25.8]


3) Effectuer une multiplication par 2 sur ces deux collections

pour effectuer une multiplication on utilise *

In [18]:
multi_temps = temperature * 2
print(multi_temps)
multi_tab = tableau * 2
print(multi_tab)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


4) Quelle différence observe-t-on ?

pour la liste les données ont étés dupliqués alors que pour le tableau chaque donnée à été multiplier par 2

# Partie 2 – Création des données

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro

on va utiliser np.zeros

In [19]:
tableau_zeros = np.zeros(10)
print(tableau_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Créer un tableau contenant 10 valeurs égales à 1.

on utilise np.ones

In [20]:
tableau_ones = np.ones(10)
print(tableau_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Créer un tableau de 10 valeurs initialisées à 25.

on va utiliser np.full

In [21]:
tableau_full = np.full((10),25)
print(tableau_full)

[25 25 25 25 25 25 25 25 25 25]


4) Créer une matrice identité de taille 5 × 5

on utilise np.eye

In [22]:
matrice_iden = np.eye(5)
print(matrice_iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Créer les 24 heures (de 0 à 23) de mesure d’une journée

on va utiliser np.arange

In [23]:
mesure_journee = np.arange(0, 24)
print(mesure_journee)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

on utilise np.linspace

In [24]:
valeur_repartie = np.linspace(20, 30, 10)
print(valeur_repartie)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

on va utiliser np.random.seed

In [25]:
np.random.seed(50)
mesures_aleatoire = np.random.uniform(10, 35, 100)
print(mesures_aleatoire)

[22.36504114 15.70207761 16.38684809 19.90824774 19.43287744 34.91435575
 20.20493001 29.29734987 29.0134172  17.75023372 18.66353011 18.79412044
 13.63667141 34.31661712 32.72946095 23.99892759 17.83976866 32.20500094
 26.86432665 19.77718619 22.6796031  23.10258757 33.2000232  24.28432673
 26.70843922 11.30646728 18.1764326  11.41004098 14.49569235 33.14832931
 33.45038057 27.85231769 28.31719022 21.54369191 33.28323169 20.16050608
 27.08014426 26.2478967  24.96912947 15.5509848  27.05892923 31.95140757
 29.91793158 20.80005619 32.94695548 29.54584194 28.14375696 13.12136734
 32.90771123 19.69277484 17.37323864 25.41828537 21.69615572 16.38347286
 30.97489722 14.46548006 15.67785427 26.49691115 21.97790613 11.83618356
 13.47400178 12.80767959 21.94462414 23.50740573 33.95177623 24.59480779
 23.16660228 33.05656722 32.98142541 16.30022162 27.06581527 34.10690297
 15.67404118 27.90042996 29.94400269 33.41877999 31.34306239 20.53864517
 10.13599672 10.87163322 10.34763414 24.72274826 19

# Partie 3 – Exploration des tableaux

1) Créer aléatoirement un tableau représentant les 24 températures d'une journée

on doit utiliser np.random.randint()

In [26]:
tb_aleatoire = np.random.randint(low=10, high=50, size=24)
print(tb_aleatoire)

[11 47 23 45 24 12 32 48 10 24 40 36 14 26 39 24 32 14 21 29 24 13 38 14]


2) Déterminer les propriétés suivantes du tableau

a) nombre de dimensions

on utilise tab.ndim

In [27]:
nb_dimension = tb_aleatoire.ndim
print(nb_dimension)

1


b) nombre de valeurs

on utilise tab.size

In [28]:
nb_valeur = tb_aleatoire.size
print(nb_valeur)

24


c) type des données

on utilise tab.dtype

In [29]:
type_donnee = tb_aleatoire.dtype
print(type_donnee)

int32


d) forme du tableau

on utilise tab.shape

In [30]:
forme_tableau = tb_aleatoire.shape
print(forme_tableau)

(24,)


# Partie 4 – Indexation et slicing

Considérant le tableau représentant les 24 températures d'une journée, afficher

1) la première mesure

In [31]:
print(tb_aleatoire[0])

11


2) la dernière mesure

In [32]:
print(tb_aleatoire[23])

14


3) la température de 8h

In [33]:
print(tb_aleatoire[7])

48


4) les températures de 8h à 12h

In [34]:
print(tb_aleatoire[7:12])

[48 10 24 40 36]


5) les températures des 6 premières heures

In [35]:
print(tb_aleatoire[0:6])

[11 47 23 45 24 12]


6) les températures des heures paires

In [36]:
print(tb_aleatoire[0::2])

[11 23 24 32 10 40 14 39 32 21 24 38]


# Partie 5 – Filtrage booléen

Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les
situations inhabituelles.

1) Afficher les températures supérieures à 30 °C

In [37]:
print(tb_aleatoire[tb_aleatoire > 30])


[47 45 32 48 40 36 39 32 38]


2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [38]:
normal= tb_aleatoire[(tb_aleatoire >=20) &(tb_aleatoire <=30)]
print(normal)

[23 24 24 26 24 21 29 24]


3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale.
Déterminer anomalies, un tableau de booléen précisant les anomalies

In [39]:
anomalie= tb_aleatoire >35
print(anomalie)

[False  True False  True False False False  True False False  True  True
 False False  True False False False False False False False  True False]


4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies

In [41]:
temps_anor = np.sum(anomalie)
print(temps_anor)

7


# Partie 6 – Manipulation des dimensions

On suppose qu’on a 5 capteurs

1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant
une journée

In [44]:
np.random.seed(50)
matrice_capteurs = np.random.randint(low=10, high=50, size=(5, 24))
print(matrice_capteurs)

[[42 21 43 40 14 16 47 16 32 15 12 41 17 14 24 45 38 37 36 36 16 30 41 31]
 [10 16 29 12 25 40 45 36 12 22 42 13 12 20 10 39 39 40 10 21 40 36 17 38]
 [34 37 23 17 46 46 10 10 29 29 11 19 39 47 33 42 29 15 38 16 11 46 30 46]
 [24 14 32 29 42 47 40 45 48 37 38 41 25 15 14 14 28 27 36 18 21 37 37 17]
 [11 18 45 13 31 13 16 25 41 32 10 21 40 43 24 36 32 47 16 40 46 41 19 10]]


2) Transformer la matrice en un tableau unidimensionnel

In [45]:
matrice_1d = matrice_capteurs.flatten()
print(matrice_1d)

[42 21 43 40 14 16 47 16 32 15 12 41 17 14 24 45 38 37 36 36 16 30 41 31
 10 16 29 12 25 40 45 36 12 22 42 13 12 20 10 39 39 40 10 21 40 36 17 38
 34 37 23 17 46 46 10 10 29 29 11 19 39 47 33 42 29 15 38 16 11 46 30 46
 24 14 32 29 42 47 40 45 48 37 38 41 25 15 14 14 28 27 36 18 21 37 37 17
 11 18 45 13 31 13 16 25 41 32 10 21 40 43 24 36 32 47 16 40 46 41 19 10]


3) Déterminer la transposée de la matrice

In [46]:
matrice_transposee = matrice_capteurs.T
print(matrice_transposee)

[[42 10 34 24 11]
 [21 16 37 14 18]
 [43 29 23 32 45]
 [40 12 17 29 13]
 [14 25 46 42 31]
 [16 40 46 47 13]
 [47 45 10 40 16]
 [16 36 10 45 25]
 [32 12 29 48 41]
 [15 22 29 37 32]
 [12 42 11 38 10]
 [41 13 19 41 21]
 [17 12 39 25 40]
 [14 20 47 15 43]
 [24 10 33 14 24]
 [45 39 42 14 36]
 [38 39 29 28 32]
 [37 40 15 27 47]
 [36 10 38 36 16]
 [36 21 16 18 40]
 [16 40 11 21 46]
 [30 36 46 37 41]
 [41 17 30 37 19]
 [31 38 46 17 10]]


4) Extraire toutes les mesures du capteur 1

In [47]:
capteur_1 = matrice_capteurs[0]
print(capteur_1)

[42 21 43 40 14 16 47 16 32 15 12 41 17 14 24 45 38 37 36 36 16 30 41 31]


5) Extraire toutes les mesures du capteur 5 

In [48]:
capteur_5 = matrice_capteurs[4]
print(capteur_5)

[11 18 45 13 31 13 16 25 41 32 10 21 40 43 24 36 32 47 16 40 46 41 19 10]


6) Extraire les mesures de tous les capteurs à 10h

In [49]:
mesures_10h = matrice_capteurs[:, 10]
print(mesures_10h)

[12 42 11 38 10]


7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h

In [50]:
mesures_capteurs_2_4 = matrice_capteurs[1:4, 8:13]
print(mesures_capteurs_2_4)

[[12 22 42 13 12]
 [29 29 11 19 39]
 [48 37 38 41 25]]
